# Generated by Django 3.1 on 2022-05-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Загружаемое фото'),
        ),
    ]
